name: Android CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'Merge')
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'zulu'
          cache: gradle

      - name: Write key
        if: github.event_name != 'pull_request'
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
          echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
          echo androidKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
          echo androidKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
          echo androidStoreFile='key.jks' >> gradle.properties
          echo ${{ secrets.KEY_STORE }} | base64 --decode > key.jks
          fi

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build all flavor variants
        run: |
          ./gradlew assembleWhatsappDebug assembleBusinessDebug -Pminify=true

      - name: Get short SHA
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Upload WhatsApp flavor artifacts
        uses: actions/upload-artifact@v4
        with:
          name: whatsapp-debug-app-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/whatsapp/debug/app-whatsapp-debug.apk

      - name: Upload Business flavor artifacts
        uses: actions/upload-artifact@v4
        with:
          name: business-debug-app-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/business/debug/app-business-debug.apk

